//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAAK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardRecord
    {
        public int AwardRecord_ID { get; set; }
        public System.DateTime AwardRecord_Date { get; set; }
        public int Award_ID { get; set; }
        public int Member_ID { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual Member Member { get; set; }
    }
}
