//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAAK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestNews
    {
        public int LatestNews_ID { get; set; }
        public string LatestNews_Title { get; set; }
        public string LatestNews_Detail { get; set; }
        public bool LatestNews_State { get; set; }
        public System.DateTime LatestNews_Startdatetime { get; set; }
        public System.DateTime LatestNews_Enddatetime { get; set; }
        public string LatestNews_Place { get; set; }
        public string LatestNews_Organizer { get; set; }
        public string LatestNews_Organizertelephonearea { get; set; }
        public string LatestNews_Organizertelephone { get; set; }
        public string LatestNews_Organizertelephoneext { get; set; }
        public string LatestNews_Presscontacts { get; set; }
        public string LatestNews_Presscontactstelephonearea { get; set; }
        public string LatestNews_Presscontactstelephone { get; set; }
        public string LatestNews_Presscontactstelephoneext { get; set; }
        public string LatestNews_Presscontactsmobile { get; set; }
        public string LatestNews_Presscontactsemail { get; set; }
        public int LatestNews_Modifier { get; set; }
        public Nullable<System.DateTime> LatestNews_Modificationdatetime { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
