//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAAK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MAAKEntities : DbContext
    {
        public MAAKEntities()
            : base("name=MAAKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artisticworks> Artisticworks { get; set; }
        public virtual DbSet<AssociationEvent> AssociationEvent { get; set; }
        public virtual DbSet<AssociationHistory> AssociationHistory { get; set; }
        public virtual DbSet<AssociationRule> AssociationRule { get; set; }
        public virtual DbSet<Award> Award { get; set; }
        public virtual DbSet<AwardRecord> AwardRecord { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<ExhibitionRecord> ExhibitionRecord { get; set; }
        public virtual DbSet<LatestNews> LatestNews { get; set; }
        public virtual DbSet<MediaReports> MediaReports { get; set; }
        public virtual DbSet<MeetingRecord> MeetingRecord { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<PositionRecord> PositionRecord { get; set; }
        public virtual DbSet<ResearchField> ResearchField { get; set; }
        public virtual DbSet<ResearchFieldRecord> ResearchFieldRecord { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
